version: '3.8'

services:
  node1:
    build: .
    environment:
      - NODE_ID=1
      - PEER_NODES=node2:8080,node3:8080
    ports:
      - "8081:8080"
    networks:
      - anti-entropy-network

  node2:
    build: .
    environment:
      - NODE_ID=2
      - PEER_NODES=node1:8080,node3:8080
    ports:
      - "8082:8080"
    networks:
      - anti-entropy-network

  node3:
    build: .
    environment:
      - NODE_ID=3
      - PEER_NODES=node1:8080,node2:8080
    ports:
      - "8083:8080"
    networks:
      - anti-entropy-network

networks:
  anti-entropy-network:
    driver: bridge 