name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Bazel
      uses: bazelbuild/setup-bazelisk@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'
        cache: false

    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: bazel-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          bazel-${{ runner.os }}-

    - name: Build
      run: |
        bazel build //...

    - name: Test
      run: |
        bazel test //... 